/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Athx2026RouteImport } from './routes/athx-2026'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as WorkoutSessionIdRouteImport } from './routes/workout.$sessionId'
import { Route as MyProgrammesSem2026RouteImport } from './routes/my-programmes.sem-2026'
import { Route as MyProgrammesBasicTrainingBlueprintPlusRouteImport } from './routes/my-programmes.basic-training-blueprint-plus'
import { Route as MyProgrammesAthx2026RouteImport } from './routes/my-programmes.athx-2026'
import { Route as MarketingSignUpRouteImport } from './routes/_marketing.sign-up'
import { Route as MarketingSignInRouteImport } from './routes/_marketing.sign-in'
import { Route as MarketingResetPasswordRouteImport } from './routes/_marketing.reset-password'
import { Route as MarketingProgrammesRouteImport } from './routes/_marketing.programmes'
import { Route as MarketingMyProgrammesRouteImport } from './routes/_marketing.my-programmes'
import { Route as MarketingForgotPasswordRouteImport } from './routes/_marketing.forgot-password'
import { Route as MarketingApparelRouteImport } from './routes/_marketing.apparel'
import { Route as MarketingAccountRouteImport } from './routes/_marketing.account'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppRaceRouteImport } from './routes/_app.race'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProgrammeRouteImport } from './routes/_app.programme'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppCalculatorRouteImport } from './routes/_app.calculator'
import { Route as MyProgrammesSem2026IndexRouteImport } from './routes/my-programmes.sem-2026.index'
import { Route as MyProgrammesBasicTrainingBlueprintPlusIndexRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.index'
import { Route as WorkoutSessionIdDoneRouteImport } from './routes/workout.$sessionId.done'
import { Route as MyProgrammesSem2026TodayRouteImport } from './routes/my-programmes.sem-2026.today'
import { Route as MyProgrammesSem2026ProgressRouteImport } from './routes/my-programmes.sem-2026.progress'
import { Route as MyProgrammesSem2026ProgrammeRouteImport } from './routes/my-programmes.sem-2026.programme'
import { Route as MyProgrammesSem2026ProfileRouteImport } from './routes/my-programmes.sem-2026.profile'
import { Route as MyProgrammesSem2026LearnRouteImport } from './routes/my-programmes.sem-2026.learn'
import { Route as MyProgrammesSem2026EventRouteImport } from './routes/my-programmes.sem-2026.event'
import { Route as MyProgrammesSem2026CalculatorRouteImport } from './routes/my-programmes.sem-2026.calculator'
import { Route as MyProgrammesBasicTrainingBlueprintPlusTodayRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.today'
import { Route as MyProgrammesBasicTrainingBlueprintPlusProgressRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.progress'
import { Route as MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.programme'
import { Route as MyProgrammesBasicTrainingBlueprintPlusLearnRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.learn'
import { Route as MyProgrammesBasicTrainingBlueprintPlusCalculatorRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.calculator'
import { Route as MyProgrammesBasicTrainingBlueprintPlusAssessmentRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.assessment'
import { Route as MyProgrammesAthx2026TodayRouteImport } from './routes/my-programmes.athx-2026.today'
import { Route as MyProgrammesAthx2026RaceRouteImport } from './routes/my-programmes.athx-2026.race'
import { Route as MyProgrammesAthx2026ProgressRouteImport } from './routes/my-programmes.athx-2026.progress'
import { Route as MyProgrammesAthx2026ProgrammeRouteImport } from './routes/my-programmes.athx-2026.programme'
import { Route as MyProgrammesAthx2026ProfileRouteImport } from './routes/my-programmes.athx-2026.profile'
import { Route as MyProgrammesAthx2026LearnRouteImport } from './routes/my-programmes.athx-2026.learn'
import { Route as MyProgrammesAthx2026CalculatorRouteImport } from './routes/my-programmes.athx-2026.calculator'
import { Route as MarketingProgrammesSlugRouteImport } from './routes/_marketing.programmes.$slug'
import { Route as AppProgrammeWWeekRouteImport } from './routes/_app.programme.w.$week'
import { Route as AppProgrammeSSessionIdRouteImport } from './routes/_app.programme.s.$sessionId'
import { Route as MyProgrammesSem2026ProgrammeSSessionIdRouteImport } from './routes/my-programmes.sem-2026.programme.s.$sessionId'
import { Route as MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRouteImport } from './routes/my-programmes.basic-training-blueprint-plus.programme.s.$sessionId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Athx2026Route = Athx2026RouteImport.update({
  id: '/athx-2026',
  path: '/athx-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const WorkoutSessionIdRoute = WorkoutSessionIdRouteImport.update({
  id: '/workout/$sessionId',
  path: '/workout/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgrammesSem2026Route = MyProgrammesSem2026RouteImport.update({
  id: '/my-programmes/sem-2026',
  path: '/my-programmes/sem-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgrammesBasicTrainingBlueprintPlusRoute =
  MyProgrammesBasicTrainingBlueprintPlusRouteImport.update({
    id: '/my-programmes/basic-training-blueprint-plus',
    path: '/my-programmes/basic-training-blueprint-plus',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyProgrammesAthx2026Route = MyProgrammesAthx2026RouteImport.update({
  id: '/my-programmes/athx-2026',
  path: '/my-programmes/athx-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSignUpRoute = MarketingSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSignInRoute = MarketingSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingResetPasswordRoute = MarketingResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProgrammesRoute = MarketingProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingMyProgrammesRoute = MarketingMyProgrammesRouteImport.update({
  id: '/my-programmes',
  path: '/my-programmes',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingForgotPasswordRoute = MarketingForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingApparelRoute = MarketingApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAccountRoute = MarketingAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppRaceRoute = AppRaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProgrammeRoute = AppProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const MyProgrammesSem2026IndexRoute =
  MyProgrammesSem2026IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusIndexRoute =
  MyProgrammesBasicTrainingBlueprintPlusIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const WorkoutSessionIdDoneRoute = WorkoutSessionIdDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => WorkoutSessionIdRoute,
} as any)
const MyProgrammesSem2026TodayRoute =
  MyProgrammesSem2026TodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesSem2026ProgressRoute =
  MyProgrammesSem2026ProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesSem2026ProgrammeRoute =
  MyProgrammesSem2026ProgrammeRouteImport.update({
    id: '/programme',
    path: '/programme',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesSem2026ProfileRoute =
  MyProgrammesSem2026ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesSem2026LearnRoute =
  MyProgrammesSem2026LearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesSem2026EventRoute =
  MyProgrammesSem2026EventRouteImport.update({
    id: '/event',
    path: '/event',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesSem2026CalculatorRoute =
  MyProgrammesSem2026CalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => MyProgrammesSem2026Route,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusTodayRoute =
  MyProgrammesBasicTrainingBlueprintPlusTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusProgressRoute =
  MyProgrammesBasicTrainingBlueprintPlusProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusProgrammeRoute =
  MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteImport.update({
    id: '/programme',
    path: '/programme',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusLearnRoute =
  MyProgrammesBasicTrainingBlueprintPlusLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute =
  MyProgrammesBasicTrainingBlueprintPlusCalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute =
  MyProgrammesBasicTrainingBlueprintPlusAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusRoute,
  } as any)
const MyProgrammesAthx2026TodayRoute =
  MyProgrammesAthx2026TodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MyProgrammesAthx2026RaceRoute =
  MyProgrammesAthx2026RaceRouteImport.update({
    id: '/race',
    path: '/race',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MyProgrammesAthx2026ProgressRoute =
  MyProgrammesAthx2026ProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MyProgrammesAthx2026ProgrammeRoute =
  MyProgrammesAthx2026ProgrammeRouteImport.update({
    id: '/programme',
    path: '/programme',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MyProgrammesAthx2026ProfileRoute =
  MyProgrammesAthx2026ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MyProgrammesAthx2026LearnRoute =
  MyProgrammesAthx2026LearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MyProgrammesAthx2026CalculatorRoute =
  MyProgrammesAthx2026CalculatorRouteImport.update({
    id: '/calculator',
    path: '/calculator',
    getParentRoute: () => MyProgrammesAthx2026Route,
  } as any)
const MarketingProgrammesSlugRoute = MarketingProgrammesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingProgrammesRoute,
} as any)
const AppProgrammeWWeekRoute = AppProgrammeWWeekRouteImport.update({
  id: '/w/$week',
  path: '/w/$week',
  getParentRoute: () => AppProgrammeRoute,
} as any)
const AppProgrammeSSessionIdRoute = AppProgrammeSSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => AppProgrammeRoute,
} as any)
const MyProgrammesSem2026ProgrammeSSessionIdRoute =
  MyProgrammesSem2026ProgrammeSSessionIdRouteImport.update({
    id: '/s/$sessionId',
    path: '/s/$sessionId',
    getParentRoute: () => MyProgrammesSem2026ProgrammeRoute,
  } as any)
const MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute =
  MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRouteImport.update({
    id: '/s/$sessionId',
    path: '/s/$sessionId',
    getParentRoute: () => MyProgrammesBasicTrainingBlueprintPlusProgrammeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/athx-2026': typeof Athx2026Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculator': typeof AppCalculatorRoute
  '/learn': typeof AppLearnRoute
  '/profile': typeof AppProfileRoute
  '/programme': typeof AppProgrammeRouteWithChildren
  '/progress': typeof AppProgressRoute
  '/race': typeof AppRaceRoute
  '/today': typeof AppTodayRoute
  '/about': typeof MarketingAboutRoute
  '/account': typeof MarketingAccountRoute
  '/apparel': typeof MarketingApparelRoute
  '/forgot-password': typeof MarketingForgotPasswordRoute
  '/my-programmes': typeof MarketingMyProgrammesRoute
  '/programmes': typeof MarketingProgrammesRouteWithChildren
  '/reset-password': typeof MarketingResetPasswordRoute
  '/sign-in': typeof MarketingSignInRoute
  '/sign-up': typeof MarketingSignUpRoute
  '/my-programmes/athx-2026': typeof MyProgrammesAthx2026RouteWithChildren
  '/my-programmes/basic-training-blueprint-plus': typeof MyProgrammesBasicTrainingBlueprintPlusRouteWithChildren
  '/my-programmes/sem-2026': typeof MyProgrammesSem2026RouteWithChildren
  '/workout/$sessionId': typeof WorkoutSessionIdRouteWithChildren
  '/programmes/$slug': typeof MarketingProgrammesSlugRoute
  '/my-programmes/athx-2026/calculator': typeof MyProgrammesAthx2026CalculatorRoute
  '/my-programmes/athx-2026/learn': typeof MyProgrammesAthx2026LearnRoute
  '/my-programmes/athx-2026/profile': typeof MyProgrammesAthx2026ProfileRoute
  '/my-programmes/athx-2026/programme': typeof MyProgrammesAthx2026ProgrammeRoute
  '/my-programmes/athx-2026/progress': typeof MyProgrammesAthx2026ProgressRoute
  '/my-programmes/athx-2026/race': typeof MyProgrammesAthx2026RaceRoute
  '/my-programmes/athx-2026/today': typeof MyProgrammesAthx2026TodayRoute
  '/my-programmes/basic-training-blueprint-plus/assessment': typeof MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute
  '/my-programmes/basic-training-blueprint-plus/calculator': typeof MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute
  '/my-programmes/basic-training-blueprint-plus/learn': typeof MyProgrammesBasicTrainingBlueprintPlusLearnRoute
  '/my-programmes/basic-training-blueprint-plus/programme': typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteWithChildren
  '/my-programmes/basic-training-blueprint-plus/progress': typeof MyProgrammesBasicTrainingBlueprintPlusProgressRoute
  '/my-programmes/basic-training-blueprint-plus/today': typeof MyProgrammesBasicTrainingBlueprintPlusTodayRoute
  '/my-programmes/sem-2026/calculator': typeof MyProgrammesSem2026CalculatorRoute
  '/my-programmes/sem-2026/event': typeof MyProgrammesSem2026EventRoute
  '/my-programmes/sem-2026/learn': typeof MyProgrammesSem2026LearnRoute
  '/my-programmes/sem-2026/profile': typeof MyProgrammesSem2026ProfileRoute
  '/my-programmes/sem-2026/programme': typeof MyProgrammesSem2026ProgrammeRouteWithChildren
  '/my-programmes/sem-2026/progress': typeof MyProgrammesSem2026ProgressRoute
  '/my-programmes/sem-2026/today': typeof MyProgrammesSem2026TodayRoute
  '/workout/$sessionId/done': typeof WorkoutSessionIdDoneRoute
  '/my-programmes/basic-training-blueprint-plus/': typeof MyProgrammesBasicTrainingBlueprintPlusIndexRoute
  '/my-programmes/sem-2026/': typeof MyProgrammesSem2026IndexRoute
  '/programme/s/$sessionId': typeof AppProgrammeSSessionIdRoute
  '/programme/w/$week': typeof AppProgrammeWWeekRoute
  '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId': typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute
  '/my-programmes/sem-2026/programme/s/$sessionId': typeof MyProgrammesSem2026ProgrammeSSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/athx-2026': typeof Athx2026Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculator': typeof AppCalculatorRoute
  '/learn': typeof AppLearnRoute
  '/profile': typeof AppProfileRoute
  '/programme': typeof AppProgrammeRouteWithChildren
  '/progress': typeof AppProgressRoute
  '/race': typeof AppRaceRoute
  '/today': typeof AppTodayRoute
  '/about': typeof MarketingAboutRoute
  '/account': typeof MarketingAccountRoute
  '/apparel': typeof MarketingApparelRoute
  '/forgot-password': typeof MarketingForgotPasswordRoute
  '/my-programmes': typeof MarketingMyProgrammesRoute
  '/programmes': typeof MarketingProgrammesRouteWithChildren
  '/reset-password': typeof MarketingResetPasswordRoute
  '/sign-in': typeof MarketingSignInRoute
  '/sign-up': typeof MarketingSignUpRoute
  '/my-programmes/athx-2026': typeof MyProgrammesAthx2026RouteWithChildren
  '/workout/$sessionId': typeof WorkoutSessionIdRouteWithChildren
  '/programmes/$slug': typeof MarketingProgrammesSlugRoute
  '/my-programmes/athx-2026/calculator': typeof MyProgrammesAthx2026CalculatorRoute
  '/my-programmes/athx-2026/learn': typeof MyProgrammesAthx2026LearnRoute
  '/my-programmes/athx-2026/profile': typeof MyProgrammesAthx2026ProfileRoute
  '/my-programmes/athx-2026/programme': typeof MyProgrammesAthx2026ProgrammeRoute
  '/my-programmes/athx-2026/progress': typeof MyProgrammesAthx2026ProgressRoute
  '/my-programmes/athx-2026/race': typeof MyProgrammesAthx2026RaceRoute
  '/my-programmes/athx-2026/today': typeof MyProgrammesAthx2026TodayRoute
  '/my-programmes/basic-training-blueprint-plus/assessment': typeof MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute
  '/my-programmes/basic-training-blueprint-plus/calculator': typeof MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute
  '/my-programmes/basic-training-blueprint-plus/learn': typeof MyProgrammesBasicTrainingBlueprintPlusLearnRoute
  '/my-programmes/basic-training-blueprint-plus/programme': typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteWithChildren
  '/my-programmes/basic-training-blueprint-plus/progress': typeof MyProgrammesBasicTrainingBlueprintPlusProgressRoute
  '/my-programmes/basic-training-blueprint-plus/today': typeof MyProgrammesBasicTrainingBlueprintPlusTodayRoute
  '/my-programmes/sem-2026/calculator': typeof MyProgrammesSem2026CalculatorRoute
  '/my-programmes/sem-2026/event': typeof MyProgrammesSem2026EventRoute
  '/my-programmes/sem-2026/learn': typeof MyProgrammesSem2026LearnRoute
  '/my-programmes/sem-2026/profile': typeof MyProgrammesSem2026ProfileRoute
  '/my-programmes/sem-2026/programme': typeof MyProgrammesSem2026ProgrammeRouteWithChildren
  '/my-programmes/sem-2026/progress': typeof MyProgrammesSem2026ProgressRoute
  '/my-programmes/sem-2026/today': typeof MyProgrammesSem2026TodayRoute
  '/workout/$sessionId/done': typeof WorkoutSessionIdDoneRoute
  '/my-programmes/basic-training-blueprint-plus': typeof MyProgrammesBasicTrainingBlueprintPlusIndexRoute
  '/my-programmes/sem-2026': typeof MyProgrammesSem2026IndexRoute
  '/programme/s/$sessionId': typeof AppProgrammeSSessionIdRoute
  '/programme/w/$week': typeof AppProgrammeWWeekRoute
  '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId': typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute
  '/my-programmes/sem-2026/programme/s/$sessionId': typeof MyProgrammesSem2026ProgrammeSSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/athx-2026': typeof Athx2026Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/calculator': typeof AppCalculatorRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/programme': typeof AppProgrammeRouteWithChildren
  '/_app/progress': typeof AppProgressRoute
  '/_app/race': typeof AppRaceRoute
  '/_app/today': typeof AppTodayRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/account': typeof MarketingAccountRoute
  '/_marketing/apparel': typeof MarketingApparelRoute
  '/_marketing/forgot-password': typeof MarketingForgotPasswordRoute
  '/_marketing/my-programmes': typeof MarketingMyProgrammesRoute
  '/_marketing/programmes': typeof MarketingProgrammesRouteWithChildren
  '/_marketing/reset-password': typeof MarketingResetPasswordRoute
  '/_marketing/sign-in': typeof MarketingSignInRoute
  '/_marketing/sign-up': typeof MarketingSignUpRoute
  '/my-programmes/athx-2026': typeof MyProgrammesAthx2026RouteWithChildren
  '/my-programmes/basic-training-blueprint-plus': typeof MyProgrammesBasicTrainingBlueprintPlusRouteWithChildren
  '/my-programmes/sem-2026': typeof MyProgrammesSem2026RouteWithChildren
  '/workout/$sessionId': typeof WorkoutSessionIdRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/programmes/$slug': typeof MarketingProgrammesSlugRoute
  '/my-programmes/athx-2026/calculator': typeof MyProgrammesAthx2026CalculatorRoute
  '/my-programmes/athx-2026/learn': typeof MyProgrammesAthx2026LearnRoute
  '/my-programmes/athx-2026/profile': typeof MyProgrammesAthx2026ProfileRoute
  '/my-programmes/athx-2026/programme': typeof MyProgrammesAthx2026ProgrammeRoute
  '/my-programmes/athx-2026/progress': typeof MyProgrammesAthx2026ProgressRoute
  '/my-programmes/athx-2026/race': typeof MyProgrammesAthx2026RaceRoute
  '/my-programmes/athx-2026/today': typeof MyProgrammesAthx2026TodayRoute
  '/my-programmes/basic-training-blueprint-plus/assessment': typeof MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute
  '/my-programmes/basic-training-blueprint-plus/calculator': typeof MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute
  '/my-programmes/basic-training-blueprint-plus/learn': typeof MyProgrammesBasicTrainingBlueprintPlusLearnRoute
  '/my-programmes/basic-training-blueprint-plus/programme': typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteWithChildren
  '/my-programmes/basic-training-blueprint-plus/progress': typeof MyProgrammesBasicTrainingBlueprintPlusProgressRoute
  '/my-programmes/basic-training-blueprint-plus/today': typeof MyProgrammesBasicTrainingBlueprintPlusTodayRoute
  '/my-programmes/sem-2026/calculator': typeof MyProgrammesSem2026CalculatorRoute
  '/my-programmes/sem-2026/event': typeof MyProgrammesSem2026EventRoute
  '/my-programmes/sem-2026/learn': typeof MyProgrammesSem2026LearnRoute
  '/my-programmes/sem-2026/profile': typeof MyProgrammesSem2026ProfileRoute
  '/my-programmes/sem-2026/programme': typeof MyProgrammesSem2026ProgrammeRouteWithChildren
  '/my-programmes/sem-2026/progress': typeof MyProgrammesSem2026ProgressRoute
  '/my-programmes/sem-2026/today': typeof MyProgrammesSem2026TodayRoute
  '/workout/$sessionId/done': typeof WorkoutSessionIdDoneRoute
  '/my-programmes/basic-training-blueprint-plus/': typeof MyProgrammesBasicTrainingBlueprintPlusIndexRoute
  '/my-programmes/sem-2026/': typeof MyProgrammesSem2026IndexRoute
  '/_app/programme/s/$sessionId': typeof AppProgrammeSSessionIdRoute
  '/_app/programme/w/$week': typeof AppProgrammeWWeekRoute
  '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId': typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute
  '/my-programmes/sem-2026/programme/s/$sessionId': typeof MyProgrammesSem2026ProgrammeSSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athx-2026'
    | '/sitemap.xml'
    | '/calculator'
    | '/learn'
    | '/profile'
    | '/programme'
    | '/progress'
    | '/race'
    | '/today'
    | '/about'
    | '/account'
    | '/apparel'
    | '/forgot-password'
    | '/my-programmes'
    | '/programmes'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/my-programmes/athx-2026'
    | '/my-programmes/basic-training-blueprint-plus'
    | '/my-programmes/sem-2026'
    | '/workout/$sessionId'
    | '/programmes/$slug'
    | '/my-programmes/athx-2026/calculator'
    | '/my-programmes/athx-2026/learn'
    | '/my-programmes/athx-2026/profile'
    | '/my-programmes/athx-2026/programme'
    | '/my-programmes/athx-2026/progress'
    | '/my-programmes/athx-2026/race'
    | '/my-programmes/athx-2026/today'
    | '/my-programmes/basic-training-blueprint-plus/assessment'
    | '/my-programmes/basic-training-blueprint-plus/calculator'
    | '/my-programmes/basic-training-blueprint-plus/learn'
    | '/my-programmes/basic-training-blueprint-plus/programme'
    | '/my-programmes/basic-training-blueprint-plus/progress'
    | '/my-programmes/basic-training-blueprint-plus/today'
    | '/my-programmes/sem-2026/calculator'
    | '/my-programmes/sem-2026/event'
    | '/my-programmes/sem-2026/learn'
    | '/my-programmes/sem-2026/profile'
    | '/my-programmes/sem-2026/programme'
    | '/my-programmes/sem-2026/progress'
    | '/my-programmes/sem-2026/today'
    | '/workout/$sessionId/done'
    | '/my-programmes/basic-training-blueprint-plus/'
    | '/my-programmes/sem-2026/'
    | '/programme/s/$sessionId'
    | '/programme/w/$week'
    | '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId'
    | '/my-programmes/sem-2026/programme/s/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athx-2026'
    | '/sitemap.xml'
    | '/calculator'
    | '/learn'
    | '/profile'
    | '/programme'
    | '/progress'
    | '/race'
    | '/today'
    | '/about'
    | '/account'
    | '/apparel'
    | '/forgot-password'
    | '/my-programmes'
    | '/programmes'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/my-programmes/athx-2026'
    | '/workout/$sessionId'
    | '/programmes/$slug'
    | '/my-programmes/athx-2026/calculator'
    | '/my-programmes/athx-2026/learn'
    | '/my-programmes/athx-2026/profile'
    | '/my-programmes/athx-2026/programme'
    | '/my-programmes/athx-2026/progress'
    | '/my-programmes/athx-2026/race'
    | '/my-programmes/athx-2026/today'
    | '/my-programmes/basic-training-blueprint-plus/assessment'
    | '/my-programmes/basic-training-blueprint-plus/calculator'
    | '/my-programmes/basic-training-blueprint-plus/learn'
    | '/my-programmes/basic-training-blueprint-plus/programme'
    | '/my-programmes/basic-training-blueprint-plus/progress'
    | '/my-programmes/basic-training-blueprint-plus/today'
    | '/my-programmes/sem-2026/calculator'
    | '/my-programmes/sem-2026/event'
    | '/my-programmes/sem-2026/learn'
    | '/my-programmes/sem-2026/profile'
    | '/my-programmes/sem-2026/programme'
    | '/my-programmes/sem-2026/progress'
    | '/my-programmes/sem-2026/today'
    | '/workout/$sessionId/done'
    | '/my-programmes/basic-training-blueprint-plus'
    | '/my-programmes/sem-2026'
    | '/programme/s/$sessionId'
    | '/programme/w/$week'
    | '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId'
    | '/my-programmes/sem-2026/programme/s/$sessionId'
  id:
    | '__root__'
    | '/_app'
    | '/_marketing'
    | '/athx-2026'
    | '/sitemap.xml'
    | '/_app/calculator'
    | '/_app/learn'
    | '/_app/profile'
    | '/_app/programme'
    | '/_app/progress'
    | '/_app/race'
    | '/_app/today'
    | '/_marketing/about'
    | '/_marketing/account'
    | '/_marketing/apparel'
    | '/_marketing/forgot-password'
    | '/_marketing/my-programmes'
    | '/_marketing/programmes'
    | '/_marketing/reset-password'
    | '/_marketing/sign-in'
    | '/_marketing/sign-up'
    | '/my-programmes/athx-2026'
    | '/my-programmes/basic-training-blueprint-plus'
    | '/my-programmes/sem-2026'
    | '/workout/$sessionId'
    | '/_marketing/'
    | '/_marketing/programmes/$slug'
    | '/my-programmes/athx-2026/calculator'
    | '/my-programmes/athx-2026/learn'
    | '/my-programmes/athx-2026/profile'
    | '/my-programmes/athx-2026/programme'
    | '/my-programmes/athx-2026/progress'
    | '/my-programmes/athx-2026/race'
    | '/my-programmes/athx-2026/today'
    | '/my-programmes/basic-training-blueprint-plus/assessment'
    | '/my-programmes/basic-training-blueprint-plus/calculator'
    | '/my-programmes/basic-training-blueprint-plus/learn'
    | '/my-programmes/basic-training-blueprint-plus/programme'
    | '/my-programmes/basic-training-blueprint-plus/progress'
    | '/my-programmes/basic-training-blueprint-plus/today'
    | '/my-programmes/sem-2026/calculator'
    | '/my-programmes/sem-2026/event'
    | '/my-programmes/sem-2026/learn'
    | '/my-programmes/sem-2026/profile'
    | '/my-programmes/sem-2026/programme'
    | '/my-programmes/sem-2026/progress'
    | '/my-programmes/sem-2026/today'
    | '/workout/$sessionId/done'
    | '/my-programmes/basic-training-blueprint-plus/'
    | '/my-programmes/sem-2026/'
    | '/_app/programme/s/$sessionId'
    | '/_app/programme/w/$week'
    | '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId'
    | '/my-programmes/sem-2026/programme/s/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  Athx2026Route: typeof Athx2026Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MyProgrammesAthx2026Route: typeof MyProgrammesAthx2026RouteWithChildren
  MyProgrammesBasicTrainingBlueprintPlusRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRouteWithChildren
  MyProgrammesSem2026Route: typeof MyProgrammesSem2026RouteWithChildren
  WorkoutSessionIdRoute: typeof WorkoutSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athx-2026': {
      id: '/athx-2026'
      path: '/athx-2026'
      fullPath: '/athx-2026'
      preLoaderRoute: typeof Athx2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/workout/$sessionId': {
      id: '/workout/$sessionId'
      path: '/workout/$sessionId'
      fullPath: '/workout/$sessionId'
      preLoaderRoute: typeof WorkoutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-programmes/sem-2026': {
      id: '/my-programmes/sem-2026'
      path: '/my-programmes/sem-2026'
      fullPath: '/my-programmes/sem-2026'
      preLoaderRoute: typeof MyProgrammesSem2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-programmes/basic-training-blueprint-plus': {
      id: '/my-programmes/basic-training-blueprint-plus'
      path: '/my-programmes/basic-training-blueprint-plus'
      fullPath: '/my-programmes/basic-training-blueprint-plus'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-programmes/athx-2026': {
      id: '/my-programmes/athx-2026'
      path: '/my-programmes/athx-2026'
      fullPath: '/my-programmes/athx-2026'
      preLoaderRoute: typeof MyProgrammesAthx2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/sign-up': {
      id: '/_marketing/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof MarketingSignUpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/sign-in': {
      id: '/_marketing/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof MarketingSignInRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/reset-password': {
      id: '/_marketing/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MarketingResetPasswordRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/programmes': {
      id: '/_marketing/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof MarketingProgrammesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/my-programmes': {
      id: '/_marketing/my-programmes'
      path: '/my-programmes'
      fullPath: '/my-programmes'
      preLoaderRoute: typeof MarketingMyProgrammesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/forgot-password': {
      id: '/_marketing/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof MarketingForgotPasswordRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/apparel': {
      id: '/_marketing/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof MarketingApparelRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/account': {
      id: '/_marketing/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MarketingAccountRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/race': {
      id: '/_app/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof AppRaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programme': {
      id: '/_app/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof AppProgrammeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculator': {
      id: '/_app/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/my-programmes/sem-2026/': {
      id: '/my-programmes/sem-2026/'
      path: '/'
      fullPath: '/my-programmes/sem-2026/'
      preLoaderRoute: typeof MyProgrammesSem2026IndexRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/basic-training-blueprint-plus/': {
      id: '/my-programmes/basic-training-blueprint-plus/'
      path: '/'
      fullPath: '/my-programmes/basic-training-blueprint-plus/'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusIndexRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/workout/$sessionId/done': {
      id: '/workout/$sessionId/done'
      path: '/done'
      fullPath: '/workout/$sessionId/done'
      preLoaderRoute: typeof WorkoutSessionIdDoneRouteImport
      parentRoute: typeof WorkoutSessionIdRoute
    }
    '/my-programmes/sem-2026/today': {
      id: '/my-programmes/sem-2026/today'
      path: '/today'
      fullPath: '/my-programmes/sem-2026/today'
      preLoaderRoute: typeof MyProgrammesSem2026TodayRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/sem-2026/progress': {
      id: '/my-programmes/sem-2026/progress'
      path: '/progress'
      fullPath: '/my-programmes/sem-2026/progress'
      preLoaderRoute: typeof MyProgrammesSem2026ProgressRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/sem-2026/programme': {
      id: '/my-programmes/sem-2026/programme'
      path: '/programme'
      fullPath: '/my-programmes/sem-2026/programme'
      preLoaderRoute: typeof MyProgrammesSem2026ProgrammeRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/sem-2026/profile': {
      id: '/my-programmes/sem-2026/profile'
      path: '/profile'
      fullPath: '/my-programmes/sem-2026/profile'
      preLoaderRoute: typeof MyProgrammesSem2026ProfileRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/sem-2026/learn': {
      id: '/my-programmes/sem-2026/learn'
      path: '/learn'
      fullPath: '/my-programmes/sem-2026/learn'
      preLoaderRoute: typeof MyProgrammesSem2026LearnRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/sem-2026/event': {
      id: '/my-programmes/sem-2026/event'
      path: '/event'
      fullPath: '/my-programmes/sem-2026/event'
      preLoaderRoute: typeof MyProgrammesSem2026EventRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/sem-2026/calculator': {
      id: '/my-programmes/sem-2026/calculator'
      path: '/calculator'
      fullPath: '/my-programmes/sem-2026/calculator'
      preLoaderRoute: typeof MyProgrammesSem2026CalculatorRouteImport
      parentRoute: typeof MyProgrammesSem2026Route
    }
    '/my-programmes/basic-training-blueprint-plus/today': {
      id: '/my-programmes/basic-training-blueprint-plus/today'
      path: '/today'
      fullPath: '/my-programmes/basic-training-blueprint-plus/today'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusTodayRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/my-programmes/basic-training-blueprint-plus/progress': {
      id: '/my-programmes/basic-training-blueprint-plus/progress'
      path: '/progress'
      fullPath: '/my-programmes/basic-training-blueprint-plus/progress'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgressRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/my-programmes/basic-training-blueprint-plus/programme': {
      id: '/my-programmes/basic-training-blueprint-plus/programme'
      path: '/programme'
      fullPath: '/my-programmes/basic-training-blueprint-plus/programme'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/my-programmes/basic-training-blueprint-plus/learn': {
      id: '/my-programmes/basic-training-blueprint-plus/learn'
      path: '/learn'
      fullPath: '/my-programmes/basic-training-blueprint-plus/learn'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusLearnRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/my-programmes/basic-training-blueprint-plus/calculator': {
      id: '/my-programmes/basic-training-blueprint-plus/calculator'
      path: '/calculator'
      fullPath: '/my-programmes/basic-training-blueprint-plus/calculator'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusCalculatorRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/my-programmes/basic-training-blueprint-plus/assessment': {
      id: '/my-programmes/basic-training-blueprint-plus/assessment'
      path: '/assessment'
      fullPath: '/my-programmes/basic-training-blueprint-plus/assessment'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusAssessmentRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusRoute
    }
    '/my-programmes/athx-2026/today': {
      id: '/my-programmes/athx-2026/today'
      path: '/today'
      fullPath: '/my-programmes/athx-2026/today'
      preLoaderRoute: typeof MyProgrammesAthx2026TodayRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/my-programmes/athx-2026/race': {
      id: '/my-programmes/athx-2026/race'
      path: '/race'
      fullPath: '/my-programmes/athx-2026/race'
      preLoaderRoute: typeof MyProgrammesAthx2026RaceRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/my-programmes/athx-2026/progress': {
      id: '/my-programmes/athx-2026/progress'
      path: '/progress'
      fullPath: '/my-programmes/athx-2026/progress'
      preLoaderRoute: typeof MyProgrammesAthx2026ProgressRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/my-programmes/athx-2026/programme': {
      id: '/my-programmes/athx-2026/programme'
      path: '/programme'
      fullPath: '/my-programmes/athx-2026/programme'
      preLoaderRoute: typeof MyProgrammesAthx2026ProgrammeRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/my-programmes/athx-2026/profile': {
      id: '/my-programmes/athx-2026/profile'
      path: '/profile'
      fullPath: '/my-programmes/athx-2026/profile'
      preLoaderRoute: typeof MyProgrammesAthx2026ProfileRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/my-programmes/athx-2026/learn': {
      id: '/my-programmes/athx-2026/learn'
      path: '/learn'
      fullPath: '/my-programmes/athx-2026/learn'
      preLoaderRoute: typeof MyProgrammesAthx2026LearnRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/my-programmes/athx-2026/calculator': {
      id: '/my-programmes/athx-2026/calculator'
      path: '/calculator'
      fullPath: '/my-programmes/athx-2026/calculator'
      preLoaderRoute: typeof MyProgrammesAthx2026CalculatorRouteImport
      parentRoute: typeof MyProgrammesAthx2026Route
    }
    '/_marketing/programmes/$slug': {
      id: '/_marketing/programmes/$slug'
      path: '/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof MarketingProgrammesSlugRouteImport
      parentRoute: typeof MarketingProgrammesRoute
    }
    '/_app/programme/w/$week': {
      id: '/_app/programme/w/$week'
      path: '/w/$week'
      fullPath: '/programme/w/$week'
      preLoaderRoute: typeof AppProgrammeWWeekRouteImport
      parentRoute: typeof AppProgrammeRoute
    }
    '/_app/programme/s/$sessionId': {
      id: '/_app/programme/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/programme/s/$sessionId'
      preLoaderRoute: typeof AppProgrammeSSessionIdRouteImport
      parentRoute: typeof AppProgrammeRoute
    }
    '/my-programmes/sem-2026/programme/s/$sessionId': {
      id: '/my-programmes/sem-2026/programme/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/my-programmes/sem-2026/programme/s/$sessionId'
      preLoaderRoute: typeof MyProgrammesSem2026ProgrammeSSessionIdRouteImport
      parentRoute: typeof MyProgrammesSem2026ProgrammeRoute
    }
    '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId': {
      id: '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/my-programmes/basic-training-blueprint-plus/programme/s/$sessionId'
      preLoaderRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRouteImport
      parentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeRoute
    }
  }
}

interface AppProgrammeRouteChildren {
  AppProgrammeSSessionIdRoute: typeof AppProgrammeSSessionIdRoute
  AppProgrammeWWeekRoute: typeof AppProgrammeWWeekRoute
}

const AppProgrammeRouteChildren: AppProgrammeRouteChildren = {
  AppProgrammeSSessionIdRoute: AppProgrammeSSessionIdRoute,
  AppProgrammeWWeekRoute: AppProgrammeWWeekRoute,
}

const AppProgrammeRouteWithChildren = AppProgrammeRoute._addFileChildren(
  AppProgrammeRouteChildren,
)

interface AppRouteChildren {
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppLearnRoute: typeof AppLearnRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgrammeRoute: typeof AppProgrammeRouteWithChildren
  AppProgressRoute: typeof AppProgressRoute
  AppRaceRoute: typeof AppRaceRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalculatorRoute: AppCalculatorRoute,
  AppLearnRoute: AppLearnRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgrammeRoute: AppProgrammeRouteWithChildren,
  AppProgressRoute: AppProgressRoute,
  AppRaceRoute: AppRaceRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MarketingProgrammesRouteChildren {
  MarketingProgrammesSlugRoute: typeof MarketingProgrammesSlugRoute
}

const MarketingProgrammesRouteChildren: MarketingProgrammesRouteChildren = {
  MarketingProgrammesSlugRoute: MarketingProgrammesSlugRoute,
}

const MarketingProgrammesRouteWithChildren =
  MarketingProgrammesRoute._addFileChildren(MarketingProgrammesRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingAccountRoute: typeof MarketingAccountRoute
  MarketingApparelRoute: typeof MarketingApparelRoute
  MarketingForgotPasswordRoute: typeof MarketingForgotPasswordRoute
  MarketingMyProgrammesRoute: typeof MarketingMyProgrammesRoute
  MarketingProgrammesRoute: typeof MarketingProgrammesRouteWithChildren
  MarketingResetPasswordRoute: typeof MarketingResetPasswordRoute
  MarketingSignInRoute: typeof MarketingSignInRoute
  MarketingSignUpRoute: typeof MarketingSignUpRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingAccountRoute: MarketingAccountRoute,
  MarketingApparelRoute: MarketingApparelRoute,
  MarketingForgotPasswordRoute: MarketingForgotPasswordRoute,
  MarketingMyProgrammesRoute: MarketingMyProgrammesRoute,
  MarketingProgrammesRoute: MarketingProgrammesRouteWithChildren,
  MarketingResetPasswordRoute: MarketingResetPasswordRoute,
  MarketingSignInRoute: MarketingSignInRoute,
  MarketingSignUpRoute: MarketingSignUpRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface MyProgrammesAthx2026RouteChildren {
  MyProgrammesAthx2026CalculatorRoute: typeof MyProgrammesAthx2026CalculatorRoute
  MyProgrammesAthx2026LearnRoute: typeof MyProgrammesAthx2026LearnRoute
  MyProgrammesAthx2026ProfileRoute: typeof MyProgrammesAthx2026ProfileRoute
  MyProgrammesAthx2026ProgrammeRoute: typeof MyProgrammesAthx2026ProgrammeRoute
  MyProgrammesAthx2026ProgressRoute: typeof MyProgrammesAthx2026ProgressRoute
  MyProgrammesAthx2026RaceRoute: typeof MyProgrammesAthx2026RaceRoute
  MyProgrammesAthx2026TodayRoute: typeof MyProgrammesAthx2026TodayRoute
}

const MyProgrammesAthx2026RouteChildren: MyProgrammesAthx2026RouteChildren = {
  MyProgrammesAthx2026CalculatorRoute: MyProgrammesAthx2026CalculatorRoute,
  MyProgrammesAthx2026LearnRoute: MyProgrammesAthx2026LearnRoute,
  MyProgrammesAthx2026ProfileRoute: MyProgrammesAthx2026ProfileRoute,
  MyProgrammesAthx2026ProgrammeRoute: MyProgrammesAthx2026ProgrammeRoute,
  MyProgrammesAthx2026ProgressRoute: MyProgrammesAthx2026ProgressRoute,
  MyProgrammesAthx2026RaceRoute: MyProgrammesAthx2026RaceRoute,
  MyProgrammesAthx2026TodayRoute: MyProgrammesAthx2026TodayRoute,
}

const MyProgrammesAthx2026RouteWithChildren =
  MyProgrammesAthx2026Route._addFileChildren(MyProgrammesAthx2026RouteChildren)

interface MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteChildren {
  MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute
}

const MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteChildren: MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteChildren =
  {
    MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute:
      MyProgrammesBasicTrainingBlueprintPlusProgrammeSSessionIdRoute,
  }

const MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteWithChildren =
  MyProgrammesBasicTrainingBlueprintPlusProgrammeRoute._addFileChildren(
    MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteChildren,
  )

interface MyProgrammesBasicTrainingBlueprintPlusRouteChildren {
  MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute: typeof MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute
  MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute: typeof MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute
  MyProgrammesBasicTrainingBlueprintPlusLearnRoute: typeof MyProgrammesBasicTrainingBlueprintPlusLearnRoute
  MyProgrammesBasicTrainingBlueprintPlusProgrammeRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteWithChildren
  MyProgrammesBasicTrainingBlueprintPlusProgressRoute: typeof MyProgrammesBasicTrainingBlueprintPlusProgressRoute
  MyProgrammesBasicTrainingBlueprintPlusTodayRoute: typeof MyProgrammesBasicTrainingBlueprintPlusTodayRoute
  MyProgrammesBasicTrainingBlueprintPlusIndexRoute: typeof MyProgrammesBasicTrainingBlueprintPlusIndexRoute
}

const MyProgrammesBasicTrainingBlueprintPlusRouteChildren: MyProgrammesBasicTrainingBlueprintPlusRouteChildren =
  {
    MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute:
      MyProgrammesBasicTrainingBlueprintPlusAssessmentRoute,
    MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute:
      MyProgrammesBasicTrainingBlueprintPlusCalculatorRoute,
    MyProgrammesBasicTrainingBlueprintPlusLearnRoute:
      MyProgrammesBasicTrainingBlueprintPlusLearnRoute,
    MyProgrammesBasicTrainingBlueprintPlusProgrammeRoute:
      MyProgrammesBasicTrainingBlueprintPlusProgrammeRouteWithChildren,
    MyProgrammesBasicTrainingBlueprintPlusProgressRoute:
      MyProgrammesBasicTrainingBlueprintPlusProgressRoute,
    MyProgrammesBasicTrainingBlueprintPlusTodayRoute:
      MyProgrammesBasicTrainingBlueprintPlusTodayRoute,
    MyProgrammesBasicTrainingBlueprintPlusIndexRoute:
      MyProgrammesBasicTrainingBlueprintPlusIndexRoute,
  }

const MyProgrammesBasicTrainingBlueprintPlusRouteWithChildren =
  MyProgrammesBasicTrainingBlueprintPlusRoute._addFileChildren(
    MyProgrammesBasicTrainingBlueprintPlusRouteChildren,
  )

interface MyProgrammesSem2026ProgrammeRouteChildren {
  MyProgrammesSem2026ProgrammeSSessionIdRoute: typeof MyProgrammesSem2026ProgrammeSSessionIdRoute
}

const MyProgrammesSem2026ProgrammeRouteChildren: MyProgrammesSem2026ProgrammeRouteChildren =
  {
    MyProgrammesSem2026ProgrammeSSessionIdRoute:
      MyProgrammesSem2026ProgrammeSSessionIdRoute,
  }

const MyProgrammesSem2026ProgrammeRouteWithChildren =
  MyProgrammesSem2026ProgrammeRoute._addFileChildren(
    MyProgrammesSem2026ProgrammeRouteChildren,
  )

interface MyProgrammesSem2026RouteChildren {
  MyProgrammesSem2026CalculatorRoute: typeof MyProgrammesSem2026CalculatorRoute
  MyProgrammesSem2026EventRoute: typeof MyProgrammesSem2026EventRoute
  MyProgrammesSem2026LearnRoute: typeof MyProgrammesSem2026LearnRoute
  MyProgrammesSem2026ProfileRoute: typeof MyProgrammesSem2026ProfileRoute
  MyProgrammesSem2026ProgrammeRoute: typeof MyProgrammesSem2026ProgrammeRouteWithChildren
  MyProgrammesSem2026ProgressRoute: typeof MyProgrammesSem2026ProgressRoute
  MyProgrammesSem2026TodayRoute: typeof MyProgrammesSem2026TodayRoute
  MyProgrammesSem2026IndexRoute: typeof MyProgrammesSem2026IndexRoute
}

const MyProgrammesSem2026RouteChildren: MyProgrammesSem2026RouteChildren = {
  MyProgrammesSem2026CalculatorRoute: MyProgrammesSem2026CalculatorRoute,
  MyProgrammesSem2026EventRoute: MyProgrammesSem2026EventRoute,
  MyProgrammesSem2026LearnRoute: MyProgrammesSem2026LearnRoute,
  MyProgrammesSem2026ProfileRoute: MyProgrammesSem2026ProfileRoute,
  MyProgrammesSem2026ProgrammeRoute:
    MyProgrammesSem2026ProgrammeRouteWithChildren,
  MyProgrammesSem2026ProgressRoute: MyProgrammesSem2026ProgressRoute,
  MyProgrammesSem2026TodayRoute: MyProgrammesSem2026TodayRoute,
  MyProgrammesSem2026IndexRoute: MyProgrammesSem2026IndexRoute,
}

const MyProgrammesSem2026RouteWithChildren =
  MyProgrammesSem2026Route._addFileChildren(MyProgrammesSem2026RouteChildren)

interface WorkoutSessionIdRouteChildren {
  WorkoutSessionIdDoneRoute: typeof WorkoutSessionIdDoneRoute
}

const WorkoutSessionIdRouteChildren: WorkoutSessionIdRouteChildren = {
  WorkoutSessionIdDoneRoute: WorkoutSessionIdDoneRoute,
}

const WorkoutSessionIdRouteWithChildren =
  WorkoutSessionIdRoute._addFileChildren(WorkoutSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  Athx2026Route: Athx2026Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MyProgrammesAthx2026Route: MyProgrammesAthx2026RouteWithChildren,
  MyProgrammesBasicTrainingBlueprintPlusRoute:
    MyProgrammesBasicTrainingBlueprintPlusRouteWithChildren,
  MyProgrammesSem2026Route: MyProgrammesSem2026RouteWithChildren,
  WorkoutSessionIdRoute: WorkoutSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
